//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chola
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccount_Payment
    {
        public int PaymentID { get; set; }
        public string RefNo { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TrxnDate { get; set; }
        public string PaymentBy { get; set; }
    }
}
