//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chola
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETicket_Passengers
    {
        public int ETicketCode { get; set; }
        public int PassengerCode { get; set; }
        public string PassengerName { get; set; }
        public string PaxType { get; set; }
        public string TicketNo { get; set; }
    }
}
