//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chola
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETicket_Itinery
    {
        public int ETicketCode { get; set; }
        public int ItineryCode { get; set; }
        public string Flight { get; set; }
        public string FlightNo { get; set; }
        public string Depart { get; set; }
        public string DepartTer { get; set; }
        public Nullable<System.DateTime> DepartDate { get; set; }
        public string DepartTime { get; set; }
        public string Arrive { get; set; }
        public string ArriveTer { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public string ArriveTime { get; set; }
        public string Class { get; set; }
        public string Baggage { get; set; }
    }
}
