//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chola
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaySlip
    {
        public int PaySlipCode { get; set; }
        public string MonthYear { get; set; }
        public string PayTo { get; set; }
        public string FINNo { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<decimal> OverTime { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<decimal> GrossPay { get; set; }
        public Nullable<decimal> CPF { get; set; }
        public Nullable<decimal> MBF { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> IncomeTax { get; set; }
        public Nullable<decimal> TotalDeductions { get; set; }
        public Nullable<decimal> Reembursement { get; set; }
        public Nullable<decimal> TotalAdditions { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> PayDay { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
